export const siteConfig = {
  name: 'ريفيو هب',
  enName: 'ReviewHub',
  description: 'High-performance tech blog',
  defaultLanguage: 'en',
  languages: {
    en: { label: 'English', dir: 'ltr' },
    ar: { label: 'العربية', dir: 'rtl' },
  },
  categories: [
    { id: "cybersecurity", en: "Cybersecurity", ar: "الأمن السيبراني" },
    { id: "ai-machine-learning", en: "AI & Machine Learning", ar: "الذكاء الاصطناعي وتعلم الآلة" },
    { id: "software-engineering", en: "Software Engineering", ar: "هندسة البرمجيات" },
    { id: "devops-cloud", en: "DevOps & Cloud", ar: "DevOps والحوسبة السحابية" },
    { id: "web-development", en: "Web Development", ar: "تطوير الويب" },
    { id: "data-engineering", en: "Data Engineering", ar: "هندسة البيانات" },
    { id: "blockchain-web3", en: "Blockchain & Web3", ar: "البلوك تشين والويب 3" },
    { id: "mobile-development", en: "Mobile Development", ar: "تطوير تطبيقات الجوال" }
  ],
  i18n: {
    en: {
      searchPlaceholder: 'Search articles...',
      readArticle: 'Read Article',
      latestArticles: 'Latest Articles',
      newestFirst: 'Newest First',
      popular: 'Popular',
      filter: 'Filter',
      loading: 'Loading...',
      heroTitle: 'Future..Tech Reviews',
      heroSubtitle: 'Discover in-depth reviews, expert analysis, and the latest trends in technology. Your guide to smarter buying decisions.',
      footerAbout: 'Your trusted source for tech reviews and buying guides.',
      copyright: 'All rights reserved',
    },
    ar: {
      searchPlaceholder: 'ابحث عن المقالات...',
      readArticle: 'اقرأ المقال',
      latestArticles: 'أحدث المقالات',
      newestFirst: 'الأحدث أولاً',
      popular: 'الأكثر شيوعاً',
      filter: 'تصفية',
      loading: 'جاري التحميل...',
      heroTitle: 'مراجعات..تقنية المستقبل',
      heroSubtitle: 'اكتشف مراجعات متعمقة، تحليلات الخبراء، وأحدث اتجاهات التكنولوجيا. دليلك لقرارات شراء أذكى.',
      footerAbout: 'مصدرك الموثوق لمراجعات التقنية وأدلة الشراء.',
      copyright: 'جميع الحقوق محفوظة',
    },
  },
  footerLinks: {
    social: [
      { name: 'Twitter', url: 'https://twitter.com', icon: 'Twitter' },
      { name: 'TikTok', url: 'https://tiktok.com', icon: 'Instagram' },
      { name: 'LinkedIn', url: 'https://linkedin.com', icon: 'Linkedin' },
      { name: 'GitHub', url: 'https://github.com', icon: 'Github' },
    ],
  },
};
